# Default values for rllopsite-deploy-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: "rllopsite"
image:
  repository: rllopdev/rllopsite
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ga-2025.02.03-1039"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "rllopapp"
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ricardllop.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.ricardllop.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ricardllop-com-tls-skmls
      hosts:
        - ricardllop.com
        - www.ricardllop.com
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
nodeSelector: {}
tolerations: []
affinity: {}
