apiVersion: v2
name: kgateway
description: A Helm chart that deploys kgateway and the public Gateway behind an Oracle Cloud NLB
version: 0.1.0

dependencies:
  - name: kgateway-crds
    version: v2.4.6
    repository: "oci://cr.kgateway.dev/kgateway-dev/charts"
  - name: kgateway
    version: v2.4.6
    repository: "oci://cr.kgateway.dev/kgateway-dev/charts"
