tailscale-operator:
  # If unset a Secret named operator-oauth must be precreated
  # This is created by terraform on the argo-cd module
  oauth: {}
  oauthSecretVolume: null
  operatorConfig:
      image:
        repo: docker.io/tailscale/k8s-operator
  proxyConfig:
    image:
      repository: docker.io/tailscale/tailscale