apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: {{ .Values.clusterIssuer.http01Gateway.name }}
            namespace: {{ .Values.clusterIssuer.http01Gateway.namespace }}
            sectionName: {{ .Values.clusterIssuer.http01Gateway.sectionName }}