ingress-nginx:
  controller:
    service:
      loadBalancerIP: "158.179.210.182"
      annotations:
        oci.oraclecloud.com/load-balancer-type: "nlb"
  namespaceOverride: ingress-nginx-free-oracle-nlb
namespace: ingress-nginx-free-oracle-nlb